name = "BilevelBenchmark.jl"
uuid = "aa819f21-2bde-4658-8897-bab36330d9b7"
authors = ["Valentin Dijon <vanadjy@gmail.com> and contributors"]
version = "0.1.0"

[deps]
Emporium = "4f286ecd-06d3-4492-bdef-0ca090b7d070"
Formatting = "59287772-0a20-5a39-b81b-1366585eb4c0"
GitHub = "bc5e4493-9b4d-5f90-b8aa-2b2bcaad7a26"

[compat]
Emporium = "0.2.4"
Formatting = "0.4"
GitHub = "5"
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
